# Generated by Django 3.2.21 on 2023-09-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
